# Generated by Django 5.1.1 on 2024-11-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbir_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="img/"),
        ),
    ]
