# Generated by Django 5.1.1 on 2024-12-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbir_app", "0002_alter_image_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="features",
        ),
        migrations.AddField(
            model_name="image",
            name="color_features",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="image",
            name="pattern_features",
            field=models.JSONField(default=list),
        ),
    ]
