# Generated by Django 5.1.4 on 2025-03-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbir_app', '0004_image_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='company_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
