# Generated by Django 5.1.4 on 2025-03-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbir_app', '0006_alter_image_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='company_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
