# Generated by Django 5.1.4 on 2025-03-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbir_app', '0007_alter_image_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.PositiveIntegerField(default=1)),
                ('company_name', models.CharField(default=None, max_length=255)),
                ('pattern_features', models.JSONField(default=list)),
                ('color_features', models.JSONField(default=list)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
