# Generated by Django 5.1.4 on 2025-03-26 10:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbir_app', '0007_alter_image_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('pattern_features', models.JSONField()),
                ('color_features', models.JSONField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
