# Generated by Django 5.1.4 on 2025-03-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbir_app', '0008_imagefeature_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/')),
                ('company_name', models.CharField(default=None, max_length=255)),
                ('pattern_features', models.JSONField(default=list)),
                ('color_features', models.JSONField(default=list)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ImageFeature',
        ),
    ]
