# Generated by Django 5.1.4 on 2025-03-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbir_app', '0008_imagefeature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageFeature',
        ),
        migrations.AddField(
            model_name='image',
            name='image_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
