# Generated by Django 5.1.4 on 2025-03-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbir_app', '0009_image_delete_imagefeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
