# Generated by Django 5.1.4 on 2025-03-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbir_app', '0010_image_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
    ]
