# Generated by Django 5.1.4 on 2025-03-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbir_app', '0010_imagefeature_remove_image_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
