# Generated by Django 5.1.4 on 2025-03-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbir_app', '0011_image_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_id',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
