# Generated by Django 5.2 on 2025-05-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbir_app', '0013_rename_color_features_image_color_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='company_name',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
