# Generated by Django 5.2 on 2025-05-17 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbir_app', '0015_rename_company_name_image_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='color_feature',
            new_name='color_features',
        ),
    ]
