# Generated by Django 5.2 on 2025-05-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbir_app', '0016_rename_color_feature_image_color_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefeature',
            name='company_name',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
