# Generated by Django 5.2 on 2025-05-17 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbir_app', '0017_alter_imagefeature_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagefeature',
            old_name='company_name',
            new_name='company_id',
        ),
    ]
