# Generated by Django 5.2 on 2025-05-17 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbir_app', '0018_rename_company_name_imagefeature_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagefeature',
            old_name='image_id',
            new_name='image_ref_id',
        ),
    ]
