# Generated by Django 5.2 on 2025-05-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbir_app', '0019_rename_image_id_imagefeature_image_ref_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='imagefeature',
            constraint=models.UniqueConstraint(fields=('company_id', 'image_ref_id'), name='unique_company_image'),
        ),
    ]
