# Generated by Django 5.2 on 2025-05-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbir_app', '0020_imagefeature_unique_company_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='filter_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='image',
            name='filter_10',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='image',
            name='filter_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='image',
            name='filter_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='image',
            name='filter_4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='image',
            name='filter_5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='image',
            name='filter_6',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='image',
            name='filter_7',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='image',
            name='filter_8',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='image',
            name='filter_9',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
