# Generated by Django 5.2 on 2025-05-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbir_app', '0021_image_filter_1_image_filter_10_image_filter_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefeature',
            name='filter_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='imagefeature',
            name='filter_10',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='imagefeature',
            name='filter_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='imagefeature',
            name='filter_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='imagefeature',
            name='filter_4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='imagefeature',
            name='filter_5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='imagefeature',
            name='filter_6',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='imagefeature',
            name='filter_7',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='imagefeature',
            name='filter_8',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='imagefeature',
            name='filter_9',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
