# Generated by Django 5.2 on 2025-05-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbir_app', '0022_imagefeature_filter_1_imagefeature_filter_10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefeature',
            name='company_id',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='imagefeature',
            name='filter_1',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='imagefeature',
            name='filter_10',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='imagefeature',
            name='filter_2',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='imagefeature',
            name='filter_3',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='imagefeature',
            name='filter_4',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='imagefeature',
            name='filter_5',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='imagefeature',
            name='filter_6',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='imagefeature',
            name='filter_7',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='imagefeature',
            name='filter_8',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='imagefeature',
            name='filter_9',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
