# Generated by Django 5.2 on 2025-05-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbir_app', '0023_alter_imagefeature_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefeature',
            name='image_ref_id',
            field=models.BigIntegerField(default=1),
        ),
    ]
