# Generated by Django 5.2 on 2025-06-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbir_app', '0024_alter_imagefeature_image_ref_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='imagefeature',
            index=models.Index(fields=['company_id', 'image_ref_id'], name='company_image_idx'),
        ),
    ]
